TYPO3:
  Flow:
    security:
      enable:
        TRUE
      authentication:
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider
            entryPoint: 'WebRedirect'
            entryPointOptions:
              routeValues:
                '@package': 'Clio.Beer'
                '@controller': 'Authentication'
                '@action':  'login'